[package]
name = "handlegraph"
version = "0.1.0"
authors = ["christian <christian@chfi.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
succinct = "0.5.2"
gfa = "0.2.1"
